# OpenEvolve Configuration for Tableaux Algorithm Optimization

max_iterations: 20
checkpoint_interval: 5

# LLM configuration
llm:
  primary_model: "gemini-2.5-flash"
  primary_model_weight: 1.0
  api_base: "https://generativelanguage.googleapis.com/v1beta/openai/"
  temperature: 0.7
  max_tokens: 2000
  timeout: 60

# Prompt configuration
prompt:
  system_message: "You are an expert Rust programmer specializing in algorithm optimization. Your task is to evolve tableaux reasoning algorithms for better performance while maintaining correctness. Key optimization targets: 1) Advanced blocking strategies, 2) Dependency-directed backtracking, 3) Heuristic rule ordering, 4) Parallel processing, 5) Memoization, 6) Early pruning. Maintain 100% logical correctness while optimizing for speed and memory efficiency."

# Database configuration
database:
  population_size: 10
  archive_size: 5
  num_islands: 2
  elite_selection_ratio: 0.2
  exploitation_ratio: 0.7

# Evaluator configuration
evaluator:
  timeout: 30
  cascade_thresholds: [0.5]
  parallel_evaluations: 2

# Evolution settings
diff_based_evolution: true
max_code_length: 30000